### ISSUE TITLE
Release 0.49 to Windows

### ISSUE THREAD

**Issue by giggio** [acaudwell/Gource#183]
Any specific reason not to release? Is it a Linux only release?

**Comment by acaudwell** [comment]
0.48-0.49 were released because of a dependency issue (GLM breaking backwards compatibility) which is only relevant to people building from source. The only feature difference is the behavior when you run gource in a submodule (it now gives you the submodule history not the parent project history).

There will be a windows build for 0.50 when that's released.

**Comment by giggio** [comment]
Ok, thanks.
