### ISSUE TITLE
[feature request] --idle-files-at-end parameter

### ISSUE THREAD

**Issue by 0jrp0** [acaudwell/Gource#247]
--file-idle-time is used to garbage collect files that haven't been touched for whatever seconds value you provide. In the visualization that I am putting together, I would like to keep the files up for almost the whole video. Except for the very end. At the end, it would be nice to artificially idle everything so the entire graph disappears into the ether leaving the background logo. I've seen this happen when specifying --file-idle-time 5, for example. However, I'd prefer that the files remain in the visualization as long as possible. 

If you can point out where in the code this could be put, perhaps I could put a small change together to support this. Thanks!

**Comment by acaudwell** [comment]
Maybe you could add a setting called `file_idle_time_at_end` (defaulting to 0.0f to be disabled). Then if you add some logic to the end of `Gource::readLog()` so that if `is_finished && gGourceSettings.file_idle_time_at_end > 0.0f` then it sets `gGourceSettings.file_idle_time = gGourceSettings.file_idle_time_at_end`. That might work.
