### ISSUE TITLE
Potential license violation in GitHub Marketplace

### ISSUE THREAD

**Issue by patrickklaeren** [acaudwell/Gource#276]
Hi - apologies if this is not the right forum to discuss this.

I came across this app which markets itself to produce visual representation of repositories. Screenshots are clearly of Gource. They do not disclose this anywhere or disclose the source anywhere.

https://github.com/marketplace/visual-source

Happy to report this, but it seems as though the options via GitHub UI are a bit vague. Wanted to check here before.

**Comment by mschilli87** [comment]
IANAL but are you sure they violoate the GPLv3 with this? Did you request the source code from them? Also, I am not sure if the GPL even covers this (unlike AGPL) since AFAICT they are running the software on 'their' server so you are being charged (if at all) for the service of running some software (looks like `gource`, I agree, but how does it matter) and giving you access to the video. What requirements does the GLP have for this use case that they don't meet?

**Comment by acaudwell** [comment]
I found on their website it does actually refer to using Gource here: https://www.visualsource.net/docs

@mschilli87's interpretation sounds about right to me. I think we would need to use a license like the AGPL to stop people making Gource as a service (GaaS) websites. Might be an opportunity there for someone to have an officially endorse one...

Thanks for raising it though.
