### ISSUE TITLE
Timeline does not re-appear when mousing over the bottom of screen

### ISSUE THREAD

**Issue by paul-uz** [acaudwell/Gource#286]
On macOS Big Sur, the timeline is visible when the window first opens, then fades away.

Mousing over the bottom of the Gource window does not make it re-appear.

**Comment by acaudwell** [comment]
Hi. Is this with the latest version 0.52? Does it happen with the previous version?

Are you using any special video parameters?

Could you also let me know your desktop video resolution?

Thanks

**Comment by paul-uz** [comment]
@acaudwell sorry, probably should have given more info!

I installed it fresh from Brew yesterday. Confirmed, its `0.52`.

Ran it without any parameters.

My desktop resolution is 3072x1920, with a second monitor plugged in thats 3840x2160

**Comment by acaudwell** [comment]
Ah k. I added support for high DPI displays but I don't have a Mac to test. It sounds like the mouse coordinates reported to the application are not correct with that feature enabled.

I could just turn that feature off by default. Unless someone wants to try and figure out the right mouse coordinates scaling to fix it?

**Comment by paul-uz** [comment]
@acaudwell I'd love to, if I had the slightest clue how to haha.

I noticed soe odd behaviour with this. If I resize the window any amount, the timeline bar does reappear, but the scaling of the view inside the window goes all wrong, so seems like you might be right with the high DPI scaling stuff.

**Comment by acaudwell** [comment]
I think I've fixed the Retina display these bugs.

Would be good if you could take another look.

You can install the development version with:

`brew install --HEAD gource`

**Comment by paul-uz** [comment]
@acaudwell it certainly looks better! The timeline is now appearing correctly, however, the tracking of the mouse when trying to scrub through is off. The mouse pointer appears behind the line marker, you cannot scrub to the very beginning or end (seems like "deadspace") and the actual accuracy of the mouse tracking is janky :/

**Comment by acaudwell** [comment]
Thanks for looking.

I think its behaving about the same as it does without a high dpi display.

It's not that intuitive but the slider position reflects the percentage of the log file, rather than reflecting the date, so its not continuous. If there's a lot of entries clumped around a date (e.g. from a big commit, often the first commit) the position will advance beyond the cursor quickly.

There is also a limitation of SDL's support for the was high resolutions work on Mac OS that means the mouse position granularity is the same as if the resolution was half, though I don't think that is that noticeable here.
