### ISSUE TITLE
"--date-format" options doesn't work

### ISSUE THREAD

**Issue by cmy2008** [acaudwell/Gource#329]
System: Windows 10 21H2
Version: 0.53
Command (PowerShell): gource.cmd  --date-format "%D" -f -1920x1080 --seconds-per-day 0.05 --auto-skip-seconds 0.1 --hide filenames
Description:
When run with a --date-format options, the date doesn't display.
![image](https://github.com/acaudwell/Gource/assets/65344456/00bd0cce-826e-4fbf-9d89-33ccbff35c93)

**Comment by pkg-dot-zip** [comment]
@cmy2008 
I think what you are trying to do is only display the day since that's what the ```"%D"``` implies, although for it to work you should use an uncapitalized letter 'd'.

Please note that just like the [README](https://github.com/acaudwell/Gource) says dates are noted in the _strftime_ format. So you could get the full date and time using:
```bash
gource --date-format "%Y-%m-%d %H:%M:%S"
```

I can not produce any issues with the current --date-format system.
