### ISSUE TITLE
Support for Unicode characters?

### ISSUE THREAD

**Issue by monyxie** [acaudwell/Gource#35]
The program displays Chinese usernames as boxes.

**Comment by pupie** [comment]
Try to replace font file gource\data\fonts\FreeSans.ttf with new font file which has Chinese characters.

**Comment by hktalent** [comment]
where is the \FreeSans.ttf ?
in mac os,thanks @pupie

**Comment by hktalent** [comment]
@pupie @monyxie 
fix 👍 
#154

**Comment by acaudwell** [comment]
There is now `--font-file` option so you can change the font to one supporting the character set.

**Comment by verhovsky** [comment]
@acaudwell could you please ship a font file that has chinese characters or if you're using system fonts, do something like what CSS does, where it looks for a list of fonts and uses the first matching one it finds, so that this works out of the box? I was impressed how `gource` on its own does exactly what I want, I'm only using it for fun, I don't care enough to configure this small thing and I don't even know where fonts are stored on my computer.
