### ISSUE TITLE
--seconds-per-day doesn't work as expected

### ISSUE THREAD

**Issue by breun** [acaudwell/Gource#96]
I have a Subversion XML log for a period of about 3 years (2005-09-30T13:03:03.947703Z to 2008-12-08T15:03:29.792001Z to be precise). When I run gource with `--seconds-per-day 0.01` I'd expect the resulting video to last under a minute (3 years * 365 days/year * 0.01 seconds/day = 10.95 seconds), but the actual resulting video is 6 minutes and 43 seconds. Is this a bug or am I missing something?

**Comment by NotMyself** [comment]
I ran into this issue today. Is it possible to get the fix merged in and new builds released including windows?

**Comment by NotMyself** [comment]
@acaudwell any idea on when a new release will go out? Trying to figure out of I need to figure out how to build gource on windows or if I should just wait a couple days for a release.

**Comment by acaudwell** [comment]
I don't have an exact time line for doing another release. Gource can be quite a lot of work to build on Windows.

I'd recommend just working around it. If you want a video to be some exact length just edit out some periods, or try other settings (--auto-skip-seconds, try smaller --seconds-per-day values).

Also this wont guarantee a the video being precise length due to various other factors (frame rate, commits buffered per frame, etc).

**Comment by NotMyself** [comment]
Ok thanks. I was under the impression that the PR had fixed it. I can always compress time in a video editor.
